config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :food_items
	get 'contact_us' => 'home#contact_us'
	get 'menu' => 'home#menu'
	get 'orders' => 'orders#new'
	get 'review' => 'home#review'
	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	def remote_image_url
		if image_url.present?
			image_url
		else
			"http://loremflickr.com/320/240/#{CGI.escape name}"
		end
	end

	def Price
		"VND "+price.to_s
	end

	def self.search(search)
	    where("name LIKE ?", "%#{search}%") 
	end

	def self.getOrder(getOrder)
	    where("name LIKE ?", "%#{getOrder}%") 
	end
end

app/models/order.rb
class Order < ApplicationRecord
	def self.getOrderNum(getOrderNum)
	    where("name LIKE ?", "%#{getOrderNum}%") 
	end
end

app/models/section.rb
class Section
	def self.all
		%w(Breakfast Lunch Dinner Supper)
	end
	def self.searchType
		%w(created_at Price)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
    if params[:search]
      @food_items = FoodItem.search(params[:search]).order("created_at DESC")
    else
      @food_items = FoodItem.all.order('created_at DESC')
    end
        
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def contact_us
  end
  def order
    if params[:getOrder]
      @food_items = FoodItem.getOrder( params[:getOrder])
    end
  end
  def review
    @ordernum = Order.find_by_id( params[:Ordernum])
    if params[:getOrder]
      @food_items = FoodItem.getOrder( params[:getOrder])
    elsif params[:Ordernum]
      @ordernum = Order.find_by_id(Ordernum)
    end
  end
  def menu
  	if params[:section] 
  		@food_items = FoodItem.order('created_at DESC').where section: params[:section]
  	elsif params[:search]
      @food_items = FoodItem.search(params[:search]).order("created_at DESC")
    elsif params[:searchType]
      @food_items = FoodItem.order( params[:searchType]+ " DESC")
    elsif params[:getOrder]
      @food_items = FoodItem.getOrder( params[:getOrder])
    elsif params[:getOrderCal]
      @food_items = FoodItem.getOrder( params[:getOrderCal])
    else
  		@food_items = FoodItem.all.order('created_at DESC')
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
     if params[:getOrder]
      @food_items = FoodItem.getOrder( params[:getOrder])
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    if params[:getOrder]
      @food_items = FoodItem.getOrder( params[:getOrder])
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
    if params[:getOrder]
      @food_items = FoodItem.getOrder( params[:getOrder])
      session[:foods_trade] = params[:getOrder]
    end
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @food_items = FoodItem.getOrder(session[:foods_trade])
    respond_to do |format|
      if @order.save
       
        format.html { redirect_to review_path(getOrder: session[:foods_trade], Ordernum: @order.id), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone_number, :address)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'form-control-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'form-control-label' %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :section, class: 'form-control-label' %>
    <%= f.text_field :section, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image_url, class: 'form-control-label' %>
    <%= f.text_field :image_url, class: 'form-control' %> 
  </div>

  <div cclass="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.remote_image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path, class: 'btn btn-secondary' %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact_us.html.erb
<h1>Where We Are</h1>

<div class = "row">
	<div class = "col-xs-3"> 
		<h3>Address</h3>
		55 Nam Kỳ Khởi Nghĩa<br>
		Nguyễn Thái Bình<br>
		Quận 1<br>
		Hồ Chí Minh<br>
		Vietnam<br>
	</div>
	<div class = "col-xs-9">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.54197983758!2d106.69947701543992!3d10.769738962260488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f405f24cb69%3A0xa0b0f41c48b780bf!2zNTUgTmFtIEvhu7MgS2jhu59pIE5naMSpYSwgTmd1eeG7hW4gVGjDoWkgQsOsbmgsIFF14bqtbiAxLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1467904399202" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome To My Restaurant</h1>
  <p class="lead">You come here to eat !!!!</p>
  <hr class="m-y-2">
  <p>We have Delicious Food	</p>
  <p class="lead">
    <!-- <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> -->
    <%= link_to "Menu", menu_path, class: 'btn btn-primary btn-lg' %>
  	<%= link_to "Contact Us", contact_us_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/home/menu.html.erb
<h1> Menu </h1>


<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Breakfast', menu_path(section: 'Breakfast'), class: 'btn btn-secondary' %>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Lunch', menu_path(section: 'Lunch'), class: 'btn btn-secondary' %>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Dinner', menu_path(section: 'Dinner'), class: 'btn btn-secondary' %>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Supper', menu_path(section: 'Supper	'), class: 'btn btn-secondary' %>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'created_at DES', menu_path(searchType: 'created_at'), class: 'btn btn-secondary btn-green' %>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Price DES', menu_path(searchType: 'Price'), class: 'btn btn-secondary btn-green' %>
</div>

<div class = "list-group">
<br>

<%= @food_items.each do |food_items| %>
	<div class = "grid">
			<div ="grid-item col-md-4">

				<button type="button" class="list-group-item">
			    	<span class="label label-default label-pill pull-xs-right">
			    		<%= food_items.Price %>
			    	</span>
			    	<div><%= food_items.name %></div>
			    	
			  	</button>
			  	<div class = "card-block">
						<%= image_tag food_items.remote_image_url %>
					</div>
					<div class="card-block" role="group" aria-label="Basic example">
				  <%= link_to 'Order Now', new_order_path(getOrder: food_items.name), class: 'btn btn-secondary btn-green' %>
					</div>
				</div>
				
			</div>


	<% end %>
		
	
</div>

app/views/home/review.html.erb
<h1>Thanks for your order, We will deliver to you soon</h1>

<div class = "row">
	
	<div class = "grid">
			<div ="grid-item col-md-4">

				<button type="button" class="list-group-item">
			    	<span class="label label-default label-pill pull-xs-right">
			    		<%= @ordernum.name %>
			    	</span>
			    	<div><%= @ordernum.phone_number %></div>
			    	<div><%= @ordernum.address %></div>
			    	
			  	</button>
				
			</div>
	<%= @food_items.each do |food_items| %>
	<div class = "grid">
			<div ="grid-item col-md-4">

				<button type="button" class="list-group-item">
			    	<span class="label label-default label-pill pull-xs-right">
			    		<%= food_items.Price %>
			    	</span>
			    	<div><%= food_items.name %></div>
			    	
			  	</button>
			  	<div class = "card-block">
						<%= image_tag food_items.remote_image_url %>
					</div>
					
				</div>
				
			</div>


	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	  <nav class="navbar navbar-light bg-faded">
	  <a class="navbar-brand" href="#">Navbar</a>
	  <ul class="nav navbar-nav">
	    <li class="nav-item <%= 'active' if current_page?(root_path) %>">
	      <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
	    </li>
	    <li class="nav-item <%= 'active' if current_page?(menu_path) %>" >
	    	<%= link_to "Menu", menu_path, class: 'nav-link' %>
	    </li>
	    <li class="nav-item <%= 'active' if current_page?(contact_us_path) %>">
	    	<%= link_to "Contact Us", contact_us_path, class: 'nav-link' %>
	    </li>
	  </ul>

	  <form class="form-inline pull-xs-right">
    
    <%= form_tag(menu_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts",  class: 'form-control' %>
      <%= submit_tag "Search", class: 'btn btn-success-outline' %>
      <% end %>
  </form>

	  <!-- <form class="form-inline pull-xs-right">
	    <input class="form-control" type="text" placeholder="Search">
	    <button class="btn btn-success-outline" type="submit">Search</button>
	  </form> -->
	</nav>
	<div class="container"</div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "row">
    <div class ="col-sm-4">
  <fieldset class="form-group">
    <%= f.label :name , class: 'form-control-label' %>
    <%= f.text_field :name , class: 'form-control' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :phone_number , class: 'form-control-label' %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :address , class: 'form-control-label' %>
    <%= f.text_area :address, class: 'form-control' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.submit  %>
  </fieldset>
</div>
 <%= @food_items.each do |food_items| %>
      <div class="col-sm-7">
            <h4 class="card-title title-text" style ="color:0184bc">
                <%= food_items.name %>
            </h4>
            
            <%= food_items.Price %>
             <div class = "parent-width">
            <%= image_tag food_items.remote_image_url %>
          </div>
            
          </div>
         
  <% end %>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table table-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.phone_number %></td>
        <td><%= order.address %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>




<%= render 'form', order: @order %>
<%= link_to 'Back', menu_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @order.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', menu_path %>